### ISSUE TITLE
disable post button

### ISSUE THREAD

**Issue by mixmix** [ticktackim/ticktack-workplan#107]
- when there's no content
- when currently publishing

**Comment by soapdog** [comment]
Working on it.

**Comment by soapdog** [comment]
Investigating an issue here. The `publish` call on `message.html.compose` is not working for me, it goes fine until it enters the callback for `prepublish` which finally calls `api.message.async.publish` but no entry is being created on my feed. It is very strange.

**Comment by soapdog** [comment]
The `api.sbot.async.publish` inside `message.async.publish` never fires the callback inside it.

**Comment by soapdog** [comment]
`sbot.async.publish` is flagging our message as invalid message and not posting it. Somehow, `type` argument to publish is wrong and the whole message object is ending up where `type` should be.

**Comment by soapdog** [comment]
It appears to be a race condition inside `ssb-feed`, somehow `working` is set to true and the messages are queued but they never leaver the queue to enter the feed.

**Comment by soapdog** [comment]
I think I have isolated the bug to be related to a broken message inside my own feed... I might need to patch something inside patchcore to be able to recover from such errors as this may happen in other peoples feed in the future.

**Comment by soapdog** [comment]
Fixed in #108

**Comment by mixmix** [comment]
I think
