### ISSUE TITLE
blob replication performance

### ISSUE THREAD

**Issue by dominictarr** [ticktackim/ticktack-workplan#109]
blobs have been reported to be loading too slowly

I hope this is because the replication protocol is overwhelmed, which I have been working on recently, and should be fixed soon.

If that works out, and blobs are still loading slowly, I'll write a thing to track the status of blob replication on each peer. It would track the number of blobs it is looking for, and on average how long it takes to retrive a blob. This won't fix the problem, but it will give us good information about how bad the problem is, and that is the first step towards fixing it properly.

**Comment by mixmix** [comment]
@dominictarr I'm closing this for the moment (no reported problems recently)
