### ISSUE TITLE
Document stack

### ISSUE THREAD

**Issue by soapdog** [ticktackim/ticktack-workplan#113]
Create a document describing the dependencies of ticktack and the reasoning behind each one, in case it is not obvious.

**Comment by soapdog** [comment]
Switching this task to document the **stack** used instead of the **dependencies** as it is more what I had in mind when I proposed it.

**Comment by soapdog** [comment]
Added to [/docs/stack.md](https://github.com/ticktackim/ticktack-workplan/blob/documentation/docs/stack.md)

**Comment by ticktackim** [comment]
@soapdog That’s awesome!


原始邮件
发件人:Andre Alves Garzianotifications@github.com
收件人:ticktackim/ticktack-workplanticktack-workplan@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年5月1日(周二) 23:35
主题:Re: [ticktackim/ticktack-workplan] Document stack (#113)


Added to /docs/stack.md
