### ISSUE TITLE
Pub improvement - add Mikey's ssb-pub

### ISSUE THREAD

**Issue by mixmix** [ticktackim/ticktack-workplan#115]

**Comment by soapdog** [comment]
I think I finally understand enough of it to upgrade our servers in a safe manner. I went to upgrade them today and got stuck due to the lack of access. I've pinged @mixmix and others who might have access to help today.

**Comment by soapdog** [comment]
I now have access to the servers.

**Comment by soapdog** [comment]
Making backup for the current `.ssb` folder.

**Comment by soapdog** [comment]
Installed docker-ce onto our **Ticktack2** pub server. Preparing for upgrade. Will need to stop current sbot process to do the upgrade.

**Comment by soapdog** [comment]
Pub server is running already. I am installing the `ssb-viewer`. Unfortunately, this requires some extra steps such as:

* installing `ssb-npm-registry` so that we have access to `git-ssb`
* installing `git-ssb`
* finally installing `ssb-viewer`

**Comment by soapdog** [comment]
Facing some problems installing the viewer. It complains about the address not being available for the viewer. I believe this might be due to the server not having a domain name. Maybe the `ssb-viewer` wants a domain.

**Comment by soapdog** [comment]
migrating second pub

**Comment by soapdog** [comment]
Just a note that there was no tmux session on `share1.ticktack.im` and no nodejs process running. For all that I see there is no pub-server currently running on it.

**Comment by soapdog** [comment]
Upgraded and running! Viewer is working as well.
