### ISSUE TITLE
Add Viewer (with blog plugin) to pubs 

### ISSUE THREAD

**Issue by mixmix** [ticktackim/ticktack-workplan#116]
I think mycognisist / glyph did this already?

**Comment by soapdog** [comment]
An enhancement to the viewer would be to make it so that the URL is embedable, on other networks.

* Open Graph tags
* Potential iframe embed

_PS: We can look at how mastodon does it_

**Comment by soapdog** [comment]
Remember that right now the pubs are using raw IP addressess and this viewer would best using domains.

**Comment by soapdog** [comment]
This is no longer blocked

**Comment by soapdog** [comment]
Got it to run as a standalone viewer. It depends on `ssb-about` but this is not documented. It works now but the server is not starting the plugin automatically. It needs to have a `serveHTTP()` call executed but apparently `sbot` is executing `init()` but not `serveHTTP()`.

**Comment by soapdog** [comment]
**IT WORKS**

http://138.68.27.255:8807/%RTXvyZ2fZWwTyWdlk0lYGk5sKw5Irj+Wk4QwxyOVG5g=.sha256

It requires some patching to the current ssb-viewer code. I've changed the code there inside `node_modules` (I know, quite ugly), I will monitor this carefully and if it is stable, I will submit it upstream.

**Comment by ticktackim** [comment]
@soapdog Do you think it will break some security in this way? Dominic is going to improve current channels/groups becoming a hash DAG. I think we may still need to figure out a way to point to a hash later then.


原始邮件
发件人:Andre Alves Garzianotifications@github.com
收件人:ticktackim/ticktack-workplanticktack-workplan@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年4月18日(周三) 03:11
主题:Re: [ticktackim/ticktack-workplan] Add Viewer (with blog plugin) topubs (#116)


IT WORKS
http://138.68.27.255:8807/%RTXvyZ2fZWwTyWdlk0lYGk5sKw5Irj+Wk4QwxyOVG5g=.sha256
It requires some patching to the current ssb-viewer code. I've changed the code there inside node_modules (I know, quite ugly), I will monitor this carefully and if it is stable, I will submit it upstream.

**Comment by soapdog** [comment]
Upgraded the second server and added the viewer as well.
