### ISSUE TITLE
Allow user to retrieve identity private key

### ISSUE THREAD

**Issue by soapdog** [ticktackim/ticktack-workplan#122]
I want a simple user interface for people to be able to export the key.

Need to talk about implementation of how you insert a key back in, and how you know when you’re up to sync with your old self (so you can post without forking)

you can move a key
it is not safe to copy and use it in both places

 *  the key can be exported with extra information such as sequence. Ticktack can wait until the new device sync up to that ordinal before allowing the user to post.
*    Danger zone: very easy to mess this up and lead to corrupt feed. Old backups can go out of sync with the current feed.

**Comment by mixmix** [comment]
Minimal things to export ? :
- [ ] secret
- [ ] gossip.json

(this could be a test in itself)

---

We also need to lock the interface from posting while a person gets in sync with themselves. We need to know which pubs to trust about where we're up to. 
This might require the Ticktack pubs to follow everyone using Ticktack... which means a change to how ticktack gets you using invites.

**Comment by mixmix** [comment]
When a user first starts Ticktack they're asked : 
- [ ] do you want to make a new identity
- [ ] do you want to restore a backup 

Then the app starts into different modes based on what they choose.

:warning: - VERY IMPORTANT to save the thing they chose and whether they are up to sync with themselves, because if we don't and they close the app they could easily fork their identity

**Comment by soapdog** [comment]
#### Plan B
If the steps mentioned [above](https://github.com/ticktackim/ticktack-workplan/issues/122#issuecomment-376005569) don't work, a potential plan B is:

* Generate a new identity
* Use an auto-invite from the new identity
* Wait for it to sync the feed for given pub key
* Replace generated identity with old identity

Basically an automation of the process we've been currently following for identity recovery. It is a bit messy, and that's why this is plan B and not plan A.

**Comment by ticktackim** [comment]
@mixmix @soapdog  
Currently, I only have designer to make ui to retrieve `Secret` file, no `gossip` file. Do you think we must need this to sync the old self? 
Besides, then do you think we should implement `pub invite code` for Sprint 4 version based on the previous Sprint 3 ui designs?

**Comment by soapdog** [comment]
@mixmix 

### Retrieving the latest sequence for a user

I've been working on our need to find _the latest sequence_ for a given user stored on our pub servers. That got me deep inside the bowels of the scuttlebot replication plugin and muxrpc (which are both a bit beyond my current understanding). While I pondered how to go forward, I had an idea which would greatly simplify this but I wanted to check with someone else before I dive deeper into this.

We'll be only checking the latest sequence with ticktack own pubs, all of which run a ssb-viewer plugin and are listening with standard HTTP protocols. I could simply craft a little url endpoint there that you pass a user id and it returns a JSON object with the latest sequence, like:

`http://share2.ticktack.im/latestsequence/@su32i2tvhf` 

returning:

``` 
{
  "id": "@su32i2tvhf",
  "latestSequence": 1246
}
```

Instead of going deep into talking to pubservers over muxrpc. What do you think? I'd much rather implement it that way.

**Comment by ticktackim** [comment]
@soapdog @mixmix Do you think we need consult with @dominic for this issue?

发自我的 iPhone

**Comment by mixmix** [comment]
hey @soapdog exposing a url could work ok as a first pass. Make it open on both pub servers for redundency...
Also, so long as you write your code modular, we can swap in how that sequence is found at a later date.
if you're modifying the pubs to do this that's fine as long as it's doesn't take more than 3 hours (made up number)? if it's going to take longer I think geting the sequence from the bowels of scuttlebot gossip is a better plan and we should just get @dominictarr to help with that.

**Comment by soapdog** [comment]
@mixmix it might be good to get input from @dominictarr, maybe he can do this in a ssb way which is better than my web way. I am not married to my solution here, it is just the solution I think I can implement because I don't think I know how to implement it from ssb gossipy side.

**Comment by soapdog** [comment]
Export is now working with the following items being added to the export file (which is in JSON format):

* The date of the export.
* The latest sequence at that time
* The peers (from gossip.json)
* The secret (from secret file)

At the moment I am not encrypting the export with a password. A good strategy is to make it all work and then add the password routines. Makes it easier to debug.

**Comment by soapdog** [comment]
I've finally got the import feature working. The code is messy right now, I am cleaning it up and pushing it. I know of some race conditions that need to be solved before we push this to the public such as "making sure that if the user closes the app in the middle of the initial sync, that the process resumes when launched again".

As a little teaser, I have it recorded at [this vimeo video](https://vimeo.com/270988835)
