### ISSUE TITLE
Sprint 4 ui designs (png, not sketch).

### ISSUE THREAD

**Issue by ticktackim** [ticktackim/ticktack-workplan#123]
@mixmix @soapdog  Below link is the png ui for your reference. I have designer improved for this third version. Please let me know if there is any question especially for the UX details.  If all UX/UI is fine, I will have designer prepare the original sketch version. Please confirm by return. 

https://storage.cloud.google.com/ticktack_ui/Sprint4%20ui.png?hl=zh-cn&_ga=2.94456476.-1003686921.1504420025

1) we need to switch back to the way to paste invite code when new users connecting with the network. 
2) we fold the my subscribed/friends' subscribed to the notifications segment.

**Comment by mixmix** [comment]
responded to this in scuttlebutt.

**Comment by mixmix** [comment]
hey @ticktackim I can no longer see the designs in this thread - I wanted to check something for the notifications, can you attach it to this thread again please (I'm getting an error about not having access priveledges to the link above)

**Comment by ticktackim** [comment]
@mixmix @soapdog  Please check below updated links for the ui designs for Sprint 4.

https://storage.cloud.google.com/ticktack_ui/Ticktack-4.png?_ga=2.144695541.-1368366881.1524795069

https://storage.cloud.google.com/ticktack_ui/ticktack%20ui_%20ver4.13.sketch?_ga=2.248832583.-1368366881.1524795069
