### ISSUE TITLE
Improve how the dynamics page displaying contents

### ISSUE THREAD

**Issue by ticktackim** [ticktackim/ticktack-workplan#125]
@mixmix @soapdog  I think we need to improve the logic of how the dynamics page displaying contents as below.

1) Displaying the latest blogs of channels that I subscribed.
2) Displaying the latest blogs that published by the authors I followed.
3) Ranking by the latest.

**Comment by soapdog** [comment]
@ticktackim I was talking with @mixmix about this issue and something crossed our mind which is with the workflow mentioned above, the user will only see content of people and channels they subscribed to in their dynamics page making it a lot more difficult for them to find new content.

I think we need to think about:

* how to make it easier for the user to see the content they are subscribed to (authors followed and channels subscribed).
* but also how to make easier for them to discover new content from people and channels which they are not subscribed.

**Comment by ticktackim** [comment]
@mixmix @soapdog This workflow is implemented on the dynamics page. so users can read this kind of active selected contents when they open dApp. If users want to search new content, they could go to the `search` page to find it, this page will show contents based on the latest which is a kind of passive selected to users. Or they could go to notifications section to search on the channels from friends’ subscription to dig out interested things.


Is it a clear logic for the content searching segment?


原始邮件
发件人:Andre Alves Garzianotifications@github.com
收件人:ticktackim/ticktack-workplanticktack-workplan@noreply.github.com
抄送:TickTackmc@ticktack.im; Mentionmention@noreply.github.com
发送时间:2018年4月2日(周一) 07:00
主题:Re: [ticktackim/ticktack-workplan] Improve how the dynamics pagedisplaying contents (#125)


@ticktackim I was talking with @mixmix about this issue and something crossed our mind which is with the workflow mentioned above, the user will only see content of people and channels they subscribed to in their dynamics page making it a lot more difficult for them to find new content.
I think we need to think about:
how to make it easier for the user to see the content they are subscribed to (authors followed and channels subscribed). but also how to make easier for them to discover new content from people and channels which they are not subscribed.

**Comment by mixmix** [comment]
Note with new stats we'll be able to update the cards too with the comments / likes / shares ! 

![selection_586](https://user-images.githubusercontent.com/2665886/39337328-77848f58-4a10-11e8-9de3-623ac88f7b99.jpg)

**Comment by ticktackim** [comment]
@soapdog Yes, I agree with what you proposed as below. The users could look for new contents at least in these two ways: 1, click on the `search` page, they can read the new contents displaying in time hash order. 2, they could click on the `friends’ subscription` to look for what is interesting from their friends’ circle.


I emphasize that the dynamics page is showing what I mentioned above is becasue this kind of contents are the one users already selected and would like to keep updates with it.


原始邮件
发件人:Andre Alves Garzianotifications@github.com
收件人:ticktackim/ticktack-workplanticktack-workplan@noreply.github.com
抄送:TickTackmc@ticktack.im; Mentionmention@noreply.github.com
发送时间:2018年4月2日(周一) 07:00
主题:Re: [ticktackim/ticktack-workplan] Improve how the dynamics pagedisplaying contents (#125)


@ticktackim I was talking with @mixmix about this issue and something crossed our mind which is with the workflow mentioned above, the user will only see content of people and channels they subscribed to in their dynamics page making it a lot more difficult for them to find new content.
I think we need to think about:
how to make it easier for the user to see the content they are subscribed to (authors followed and channels subscribed). but also how to make easier for them to discover new content from people and channels which they are not subscribed.

**Comment by mixmix** [comment]
we've listed organised by blogs by timestamp

**Comment by mixmix** [comment]
We're going to make a small filter at the top of the page which says  : 

> `  ALL  |   SUBSCRIPTSIONS   |   FRIENDS  `
