### ISSUE TITLE
Notification hanger

### ISSUE THREAD

**Issue by mixmix** [ticktackim/ticktack-workplan#131]
This is one part of the [Notifications Stats Epic](https://github.com/ticktackim/ticktack-workplan/issues/119)

![image](https://user-images.githubusercontent.com/2665886/38646020-6d0f3bea-3e3a-11e8-84c0-81fb1db7d89e.png)

**Comment by mixmix** [comment]
@ticktackim  I've made the beautiful graph, Andre is reviewing it. It was the bulk of the work because it involved sorting large amounts of data.

I'm now starting into this. What I've realised is that this dropdown is going to be a problem:
- too many likes and comments will make it really really full and intense
- there's no place for the author to easily click to reply

I want to make the default view under the  :bell:  to be the `Stats` page, but the user can also go to the sidebar to get the comments / likes / shares in a calm way.
![selection_588](https://user-images.githubusercontent.com/2665886/39338471-1264764a-4a17-11e8-8d03-a16999db70d2.jpg)

I think this is the best of both worlds : 
- allows high level overview (stats)
- allows easy replies and more detailed look at data, but in a calm way which isn't confusing

**Comment by mixmix** [comment]
I'm going to start building this and we can see how it feels. The data underneath is similar, so if it's no good we can change it.

cc @soapdog

**Comment by ticktackim** [comment]
@mixmix No problem. Let’s go and see.

发自我的 iPhone

**Comment by soapdog** [comment]
@mixmix and @ticktackim I think that making stats the default view for 🔔 is a good idea. I suspect that the dropdown (doorhanger) might be less usefull as more data comes in. I will wait for @mixmix judgement on how he wants to proceed on it. For me, the stats page alone is already useful and beautiful
