### ISSUE TITLE
Blog + Long Posts

### ISSUE THREAD

**Issue by mixmix** [ticktackim/ticktack-workplan#136]
add a setting to the settings page which toggles the display of "Long posts" 

places this is relevant:
- [ ] Dynamics page (main blogs index/  home page)
- [ ] search page (channels)
- [ ] user profile
- [ ] stats page

**Comment by mixmix** [comment]
Current behaviour: 
- [ ] Dynamics page (main blogs index/  home page)
  - shows only `blog` type messages
- [ ] search page (channels)
  - shows `blog` and long post
- [ ] user profile
  - shows `blog` and long post
- [ ] stats page
  - shows `blog` and long post

**Comment by mixmix** [comment]
This has been a longer conversation. The agreement to display things like this was made in this previous issue:
https://github.com/ticktackim/ticktack-workplan/issues/74#issuecomment-365826751

**Comment by ticktackim** [comment]
@mixmix  so what is the exact criteria of the `blog` type? Is the one users using Ticktack to publish message content larger than 2500 characters?

**Comment by ticktackim** [comment]
@mixmix  oh, I understand the `blog` type is only fit for Ticktack. Users who write a blog in Ticktack will show as `blog` type no matter what is the size of message, correct?

**Comment by mixmix** [comment]
Messafe type is a low level scuttlebutt thing. Like is another type,
subscribe is another type.
By default ticktack uses :
- blog type for all publications (this allows long form writing)
- post type (encrypted) for private messages
- post type for comments on a blog

We use post type because the other clients already use this so it's
compatible to send messages and anyone in any client to read them.

In Patchwork, post type is used for all threads. This has a limitation
though in that the writing has to be less than 8kB. But, there are a lot of
long posts that people put forward to share their ideas.
If we include post type bigger than 2.5kB (or 2500 ascoli characters) then
we can get more content which could be interesting to readers shown in
Ticktack. The size limit is just my best guess about how to avoid small
post messages which are not really articles / writing. Like people posting
a single question, or a photograph. If we include post type I want to make
sure we don't just accidentally make something which includes heaps of
junk!

**Comment by ticktackim** [comment]
@mixmix  Yes, I think adding `post` type message larger than 2.5kb (is it a 5min read time standard?) to Ticktack is a good try. We could tune the `filter` feature based on enough good content then.

**Comment by mixmix** [comment]
All places now take into account long `post` type messages (2500 characters): 

Page | shows `blog` tpye | shows long `post` type
---|---|---
Dynamics (main blogs index/  home page) | :white_check_mark: | :white_check_mark: 
Search (channels) | :white_check_mark: | :white_check_mark: 
User profile | :white_check_mark: | :white_check_mark: 
Sats | :white_check_mark: | :white_check_mark: 

---

I don't know if this is a good measure of a 5 minute read. But I think when I open the posts that are this length, there is usually enough writing that a person is sharing something a little more deep, which feels like a good fit
