### ISSUE TITLE
The filter feature seems doesn't work well. 

### ISSUE THREAD

**Issue by ticktackim** [ticktackim/ticktack-workplan#163]
The filter feature seems doesn't work well. 

1. The post of people I followed showing up on section `Search` but not on `Dynamics Friends`.
2. The section `Subscriptions` didn't show the latest updated post replication.

**Comment by mixmix** [comment]
1. hey @ticktackim the different results in different places is related to this issue https://github.com/ticktackim/ticktack-workplan/issues/136
The main Dynamics page only shows `blog` type messages. These are blogs written in Ticktack. The other places currently allow "`post` type messages longer than 2500 characters" to be shown as well. Please discuss this topic on https://github.com/ticktackim/ticktack-workplan/issues/136

---

> 2. "The section Subscriptions didn't show the latest updated post replication"

Can you explain in more detail please. Do you mean : 
1. on the Dynamics page, under `Subscriptions` filter you expected to see something different? 
2. on the Dynamics page, under `My Subscriptions` (on the side bar) you expected to see something different? 

If you can tell me where exactly you mean (with words or a screenshot), and then tell me **what you expected to see** and **what you saw which was wrong** then it's a lot easier to solve :) 
It's useful to know where exac

**Comment by ticktackim** [comment]
@mixmix Now I understand the `filter` is only for `blog` type, correct? So I reckon there is no user writing `blog` within this month in Ticktack for the channel I subscribed, am I right?
![2018-06-09 2 05 45](https://user-images.githubusercontent.com/30351648/41188357-90a7443a-6bee-11e8-92ce-37e5179ea620.png)

**Comment by mixmix** [comment]
Correct. You child test this by subscribing to a channel of something more
recent in the All fikter.

I think the app should show the same content everywhere. Or if we show post
type messages that we should label then as not blogs...
Do you think we should add post type messages to the Dynamics page (or make
this an option?)

**Comment by ticktackim** [comment]
![2018-06-10 12 24 40](https://user-images.githubusercontent.com/30351648/41198305-4ec73622-6ca9-11e8-813f-644d0e2e5a98.png)

@mixmix  I subscribed to the channel that Ted posted recently. But it is still not shown in the `Dynamics Subscriptions` section even after I restart Ticktack. Is it because I should subscribe to it before the post has been published?

**Comment by mixmix** [comment]
that could be a legitamite bug, thanks for giving a really specific case, makes it easy to check

**Comment by mixmix** [comment]
I think I've fixed all the filters.
 This particular post doesn't show up because it's less that 2500 characters long - i.e. it's too short to be displayed as a "blog"

I'm marking this as done as I'm fairly sure I've fixed this.
We can open it again if I missed anything
