### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by mixmix** [ticktackim/ticktack-workplan#70]
my subscribed channels
my friends subjscribed channels

**Comment by mixmix** [comment]
hey @ticktackim just a small english tweak - ~~reflesh~~  ➡️ refresh  (re means do again, fresh means clean or new. Flesh is like meat 🍗 !)

**Comment by mixmix** [comment]
the alignment issue of Friends Subscriptions is already:

![image](https://user-images.githubusercontent.com/2665886/36012097-a57853b8-0dc0-11e8-8c01-64453fd288f3.png)

Did you want the words to not wrap ? 
like 
```
My subscriptions
```

```
My
subscriptions
```

**Comment by ticktackim** [comment]
Thanks for the correction:-)

发自我的 iPhone

**Comment by ticktackim** [comment]
@mixmix Yes, good job!

发自我的 iPhone

**Comment by mixmix** [comment]
doing this style change now

**Comment by mixmix** [comment]
fixed with above commit ^

**Comment by mixmix** [comment]
opening a new issue for Plan B @soapdog
