### ISSUE TITLE
Favourites

### ISSUE THREAD

**Issue by mixmix** [ticktackim/ticktack-workplan#71]
I think we can add this later after subscriptions is in place

**Comment by soapdog** [comment]
To implement favorites, we might need a new message type. 

@mixmix what do you think about creating a new type of message to flag messages as favorite. I was thinking something similar to block/unblock or the subscribe/unsubscribe, with the new message having a boolean saying if the related message is _favorite_ or _remove from favorite_.

**Comment by mixmix** [comment]
Wait for josiah's tag work.
