### ISSUE TITLE
`blog` vs `post`

### ISSUE THREAD

**Issue by mixmix** [ticktackim/ticktack-workplan#74]
make the app consistent in its display of content.

We need a global definition of what to show. At the moment places to look:
- Dyanmics
- User profile
- Search

**Comment by mixmix** [comment]
Current solution for Blog vs Post type: 
- main page : only shows blogs
- other pages : show blogs + any post longer that 800 characters (so you don't see small silly messages)

**Comment by ticktackim** [comment]
@mixmix what about if a post with photo but less than 800 characters?

发自我的 iPhone

**Comment by mixmix** [comment]
Yep can make that but don't think it's a blog post. Sounds more like
Instagram. I think it's important to help people know what to expect when
they open ticktack
