### ISSUE TITLE
Setup and open ICON

### ISSUE THREAD

**Issue by ticktackim** [ticktackim/ticktack-workplan#82]
@mixmix  the new app icon is blur. I am not sure if github has extracted the files uploaded.  So I re-upload it in zip as below. 
![d_awp x 2 x uyna tlwg7](https://user-images.githubusercontent.com/30351648/36110862-27155132-105f-11e8-9bbb-4561f347c22b.png)

[app-icon.zip](https://github.com/ticktackim/ticktack-workplan/files/1717236/app-icon.zip)

**Comment by mixmix** [comment]
hey @ticktackim this doesn't meet the specs. The size is right but we need copies where the file format is  `.ico` and `.icns` (not `.png`).

If your designer can't do this let me know. I can make an ico and I might be able to make an icns with some tool online.

----

Regarding the design of that install icon, it's not good one, look what it looks like when it's small: 

![selection_505](https://user-images.githubusercontent.com/2665886/36011741-3e2a4fe2-0dbe-11e8-94e9-b2bf455a7752.jpg)

How about something simple like the logo but some simple difference like a download arrow, or something. This is something I made in 1 minute, so it's ugly but meant to give the rough idea: 

![image](https://user-images.githubusercontent.com/2665886/36011981-fcc941e6-0dbf-11e8-8c4c-ddc78a604ae6.png)

**Comment by ticktackim** [comment]
@mixmix Would you please try below one again? If still not good, we could use what you proposed first.

[ticktack512.ico.zip](https://github.com/ticktackim/ticktack-workplan/files/1711032/ticktack512.ico.zip)

**Comment by mixmix** [comment]
@ticktackim I can use that one, but it's going to be very confusing - they will not be able to see the ticktack logo because it's so small

I still need an `*.icns` files for mac.

---

If you're on plane I will just solve this problem :)

**Comment by ticktackim** [comment]
@mixmix I will on the plane very early tomorrow morning. I will invite the designer later to this repo and let him throw the file directly on it. If he can't make it on time, please just solve it at your end before official launch on Feb.11 say Beijing time 15:00.

Thanks!
2018-02-10 



mc 



发件人： mix irving 
发送时间： 2018-02-10  06:55:11 
收件人： ticktackim/ticktack-workplan 
抄送： TickTack; Mention 
主题： Re: [ticktackim/ticktack-workplan] Setup and open ICON (#82) 
 
@ticktackim I can use that one, but it's going to be very confusing - they will not be able to see the ticktack logo because it's so small
I still need an *.icns files for mac.



If you're on plane I will just solve this problem :)

**Comment by Jackwz08** [comment]
@mixmix 
[ticktack512icns 2.zip](https://github.com/ticktackim/ticktack-workplan/files/1714028/ticktack512icns.2.zip)

**Comment by mixmix** [comment]
for future, here's a good site for converting : https://iconverticons.com/online/
makes icns and ico files that seem to work well

**Comment by ticktackim** [comment]
@mixmix thanks!
@Jackwz08 please note!


发自我的 iPhone

**Comment by Jackwz08** [comment]
@ticktackim I'm already using it.
![2018-02-12 6 30 50](https://user-images.githubusercontent.com/36327534/36092601-e32cdee0-1022-11e8-8d50-4b5a04bab879.png)
