### ISSUE TITLE
scuttle-blog (make a blog reading tool for other clients / apps)

### ISSUE THREAD

**Issue by mixmix** [ticktackim/ticktack-workplan#89]
I'm going to make this and get it installed in Patchwork

**Comment by soapdog** [comment]
Is it being added to patchcore?

**Comment by mixmix** [comment]
Probably not, I'll open a PR on patchbay to show you it in a bit

**Comment by mixmix** [comment]
scuttle-blog exists and is in use in Patchbay + Patchwork
