### ISSUE TITLE
Load only some subscriptions

### ISSUE THREAD

**Issue by mixmix** [ticktackim/ticktack-workplan#95]
This is a tuning of the Subscriptions feature https://github.com/ticktackim/ticktack-workplan/issues/70#issuecomment-364317547 : 
> @soapdog I'd still like to implement Plan B if you still have time to improve this part. Since 10 channels listing would be more efficient, and with reflesh button will have better interaction with the users especially when ticktack goes mobile.

**Comment by mixmix** [comment]
picking this up now.
Also making it so it doesn't show you subscriptions you already have

**Comment by mixmix** [comment]
resolved in this PR : https://github.com/ticktackim/ticktack-workplan/pull/98

**Comment by soapdog** [comment]
@mixmix thanks for picking it up.
